### ISSUE TITLE
Issues with CUDA and Torch following the set up instructions

### ISSUE THREAD

**Issue by bazyagami** [autonomousvision/transfuser#313]
Hello,
I am attempting to run transfuser for an experiment and I am dealing with the following error :
RuntimeError: CUDA error: no kernel image is available for execution on the device
The error precisely occurs in line 742 in model.py file. 
Some information about my compute instance : 
GPU : NVIDIA A2
CUDA Version : 12.6
CUDA Capability : sm_86

Before the backbone models are loaded, I get the following warning : 
"UserWarning: 
NVIDIA A2 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70."

Can you please let me know if there is any fix to this?

Thank you.

**Comment by bazyagami** [comment]
never mind, i have fixed it. 
for anyone dealing with the same issues, these links must be a useful look up:
https://discuss.pytorch.org/t/sm-86-is-not-compatible-with-current-pytorch-version/151606
https://pytorch.org/get-started/previous-versions/
https://mmcv.readthedocs.io/en/v1.5.3/get_started/installation.html
